/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dfe8ff",
        "on-tertiary-container": "#fdfcff",
        "secondary-fixed": "#c8e6ff",
        "secondary": "#00658f",
        "outline-variant": "#c3c6d6",
        "background": "#f9f9ff",
        "on-surface": "#111c2d",
        "primary": "#1f53c9",
        "primary-container": "#406de4",
        "tertiary-container": "#637692",
        "on-secondary-fixed-variant": "#004c6d",
        "secondary-container": "#48bdfe",
        "on-primary-fixed-variant": "#003daa",
        "on-secondary-container": "#004a6b",
        "on-surface-variant": "#434654",
        "surface-tint": "#2355cc",
        "outline": "#747685",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#d8e2fb",
        "on-primary-fixed": "#00174c",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "surface-container-low": "#f1f3ff",
        "inverse-on-surface": "#ecf0ff",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#e8eeff",
        "primary-fixed-dim": "#b4c5ff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#86ceff",
        "inverse-surface": "#273143",
        "on-secondary-fixed": "#001e2e",
        "tertiary-fixed": "#d3e3ff",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed": "#061c34",
        "on-primary": "#ffffff",
        "tertiary": "#4a5d78",
        "surface-dim": "#d0daf3",
        "on-primary-container": "#fefcff",
        "surface-container-highest": "#d8e2fb",
        "on-tertiary": "#ffffff",
        "on-background": "#111c2d",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
